name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKER }}" | docker login -u "vikesh82" --password-stdin
        docker image build -t vikeshkumar8210/realtime_violencedetection:v1.
        docker push vikesh82/realtime_violencedetection:v1
